# command example to convert json to hcl2
#packer hcl2_upgrade -with-annotations .\img-mgr-packer.json
variable "aws_instance_type" {
  type    = string
  default = "t3.large"
}

variable "aws_region" {
  type    = string
  default = "us-west-2"
}

variable "aws_source_ami" {
  type    = string
  default = "amzn2-ami-hvm-2*"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_name = "my-ami-${local.timestamp}"
  associate_public_ip_address = true
  instance_type = "${var.aws_instance_type}"
  region= "${var.aws_region}"
  source_ami_filter {
    filters = {
      name = "${var.aws_source_ami}"
      virtualization-type = "hvm"
      root-device-type = "ebs"
    }
    owners = [
      "amazon"]
    most_recent = true
  }
  ssh_username = "ec2-user"
  tags = {
    application = "img-mgr"
    created-by  = "packer"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "file" {
    destination = "/tmp/install_my_app.sh"
    source      = "install_my_app.sh"
  }

  provisioner "shell" {
    inline = ["sudo sh /tmp/install_my_app.sh"]
  }

}
