AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Default: ''
    Description: (optional) Name for the S3 bucket
    Type: String
  TableName:
    Default: ''
    Description: (optional) Name for the DynamoDB table
    Type: String
Conditions:
  BucketNameOmitted: !Or
    - !Equals
      - !Ref 'BucketName'
      - ''
    - !Equals
      - !Ref 'BucketName'
      - undefined
  TableNameOmitted: !Or
    - !Equals
      - !Ref 'TableName'
      - ''
    - !Equals
      - !Ref 'TableName'
      - undefined
Description: Terraform State Resources
Resources:
  ManagementPolicy:
    Properties:
      Description: Managed policy for Terraform state management.
      Path: /
      PolicyDocument:
        Statement:
          - Action:
              - s3:ListBucket
            Effect: Allow
            Resource:
              - !GetAtt 'TerraformStateBucket.Arn'
          - Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - !GetAtt 'TerraformStateBucket.Arn'
                  - /*
          - Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - !GetAtt 'TerraformStateTable.Arn'
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  TerraformStateBucket:
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !If
        - BucketNameOmitted
        - !Ref 'AWS::NoValue'
        - !Ref 'BucketName'
      LifecycleConfiguration:
        Rules:
          - NoncurrentVersionExpirationInDays: 90
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled
    Type: AWS::S3::Bucket
  TerraformStateTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: !If
        - TableNameOmitted
        - !Ref 'AWS::NoValue'
        - !Ref 'TableName'
    Type: AWS::DynamoDB::Table
Outputs:
  PolicyArn:
    Description: Managed policy Arn
    Value: !Ref 'ManagementPolicy'
  TerraformStateBucketArn:
    Description: Arn of bucket storing Terraform state
    Value: !GetAtt 'TerraformStateBucket.Arn'
  TerraformStateBucketName:
    Description: Name of bucket storing Terraform state
    Value: !Ref 'TerraformStateBucket'
  TerraformStateTableName:
    Description: Name of DynamoDB table for Terraform state
    Value: !Ref 'TerraformStateTable'


