service: hello-world
package:
  exclude:
    - node_modules\**
provider:
  name: aws
  runtime: python3.7
  memorySize: 128

functions:
  hellopath:
    handler: lambda/index.lambda_handler
    events:
      - http:
          path: hello
          method: get
resources:
  Outputs:
    LamdaName:
      Value: !Ref HellopathLambdaFunction
    LambdaARN:
      Value: !GetAtt HellopathLambdaFunction.Arn