service: display-api
package:
  exclude:
    - 'node_modules/**'
provider:
  name: aws
  runtime: ruby2.5
  logRetentionInDays: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - ${cf:cfn-res-mgr-demo.StateManagerArn}

functions:
  lookup:
    environment:
      STATE_TBL_NAME: ${cf:cfn-res-mgr-demo.StateManagerName}
    handler: handler.lambda_handler
    events:
      - http:
          path: get_heads
          method: get
          cors: true
resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]
  Outputs:
    S3Bucket:
      Value: !Ref StaticSite
    S3BucketWebSite:
      Value: !GetAtt StaticSite.WebsiteURL
